### ISSUE TITLE
Extracting frames跑YouTubeClips视频数据时会报video_id = id2vid[video_id]这行代码的错误

### ISSUE THREAD

**Issue by Kohaku233** [yangbang18/Non-Autoregressive-Video-Captioning#2]
具体错误是KeyError: 'YouTubeClips\\-4wsuPCjDBc_5_15'，查看了VC_data\Youtube2Text后发现可能现在下载的Youtube视频数据集的名称和pkl中映射的名称不相同，请问该如何解决呢？

**Comment by yangbang18** [comment]
`-4wsuPCjDBc_5_15`是`{Youtube id}_{start_time}_{end_time}`的简写。

extracting frames中`video_id = id2vid[video_id]`的 `video_id`对映上面的`Youtube id`，是一个固定11位的字符串，你可以这么修改:

```python
import os
key = "YouTubeClips\-4wsuPCjDBc_5_15"
video_id = os.path.basename(key)  # “-4wsuPCjDBc_5_15”
video_id = video_id[:11] # “-4wsuPCjDBc”
video_id = id2vid[video_id]
```
