### ISSUE TITLE
the 3d features extraction 

### ISSUE THREAD

**Issue by HXYNODE** [yangbang18/Non-Autoregressive-Video-Captioning#4]
hi, yang!
thanks for ur great work.
i am attempting to reproduce ur work but i fail to extract the 3d features with the rough description provided in kenshohara‘s repo. 
could u detail the 3d feature extraction process, especially how to set the arguments, e.g. the overlap 8, and how to properly integrates extracted results with ur work.
besides, the results' format generated by kenshohara's repo is a json file that is apparently not adaptive to ur work.
for accurately reproducing this work, please supply more cues.
thanks a lot!

**Comment by yangbang18** [comment]
I have updated README, where you can follow the instructions now.
