### ISSUE TITLE
mapping issues

### ISSUE THREAD

**Issue by HXYNODE** [yangbang18/Non-Autoregressive-Video-Captioning#5]
hi Yang,
in youtube_mapping.txt  u provide, the video_id starts from 1 to 1970, while the vid inside in both refs.pkl and info_corpus.pkl starts from 0 to 1969. 
so there is a mismatch and i do not know if it will further endanger the training or testing process ? 
thanks!

**Comment by yangbang18** [comment]
vids in our implementation are identical to those in youtube_mapping.txt, but we rename all vids for convenience, e.g., `video0` (ours) is the same as `vid1` (.txt).
