### ISSUE TITLE
提取3d motion features 出错！

### ISSUE THREAD

**Issue by zmxsss** [yangbang18/Non-Autoregressive-Video-Captioning#7]
run   yangbang18/video-classification-3d-cn/main.py出错，错误原因是  opt.arch == model_data['arch']，该如何解决？

**Comment by yangbang18** [comment]
```
opt.arch = '{}-{}'.format(opt.model_name, opt.model_depth) 
# by default, opt.arch == `resnext-101`
# you can change this by passing arguments `--model_name` and `--model_depth`
```
请确保你从[pretrained model](https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M)中下载了正确的模型，即`resnext-101-kinetics.pth`([download url](https://drive.google.com/file/d/1cULocPe5YvPGWU4tV5t6fC9rJdGLfkWe/view?usp=sharing))
